name: Discord Release Notifications (Stable)

on:
  release:
    types: [published]  # Stable releases only

permissions:
  contents: read

jobs:
  github-releases-to-discord:
    if: ${{ !github.event.release.draft && !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "4760230"
          username: "Trailarr Releases"
          avatar_url: "https://github.com/nandyalu/trailarr/blob/dfb7b1ba80d6c82c63b4177a514d901507ba202f/assets/images/trailarr-192.png"
          # content: "ðŸš€ New Trailarr release is available!"
          footer_title: "Trailarr"
          footer_timestamp: true
          # reduce_headings: true